#!/bin/bash

SOURCE_DIR=~/git/netkiller.github.io
TARGET_DIR=~/workspace/netkiller.sourceforge.net
PUBLIC_HTML=~/workspace/

mkdir -p $TARGET_DIR

#echo "find $SOURCE_DIR -type d | egrep -v '(zh-tw|.svn|.git)'"
    for dir in $(find $SOURCE_DIR -type d | egrep -v '(zh-tw|.svn|/.git)' | sed -e "s:^$SOURCE_DIR/::g"); 
    do
        mkdir -p $TARGET_DIR/$dir
    done

    for file in $(find $SOURCE_DIR -type f | egrep -v '(zh-tw|.svn|/.git)' )
    do
 	output_file=$(echo $file | sed -e "s:^$SOURCE_DIR:$TARGET_DIR:g") # -e "s:^/::g")
        if [ "${file##*.}" = "html" ]
        then 
            	cconv -f UTF8-CN -t UTF8-HK $file -o $output_file &
        else
        
        	cp $file $output_file &
        fi
	echo $file
    done 




# sftp://netkiller,netkiller@web.sourceforge.net:/home/groups/n/ne/netkiller/htdocs
# rsync -auzv --delete * netkiller@frs.sourceforge.net:/home/user-web/n/ne/netkiller/htdocs/
#RSYNC="rsync --archive --update --compress --delete --progress --stats --exclude=.svn"
#RSYNC="rsync --archive --update --compress --delete --stats --exclude=.svn"

RSYNC="rsync --archive --compress --delete --stats -vP --exclude=.svn"
REMOTE="netkiller,netkiller@web.sourceforge.net:/home/groups/n/ne/netkiller/htdocs"
LOCAL="${PUBLIC_HTML}/netkiller.sourceforge.net"

if [ -z $1 ]; then
    #./sitemaps http://netkiller.sourceforge.net | gzip > ${LOCAL}/sitemaps.xml.gz
    eval "$RSYNC $LOCAL/* $REMOTE"
else
    $RSYNC $LOCAL/$1 $REMOTE
fi

#./sitemaps http://netkiller.sourceforge.net > /tmp/sitemap.xml
#$RSYNC /tmp/sitemaps.xml.gz /tmp/sitemap.xml $REMOTE
#$RSYNC /tmp/sitemaps.xml.gz $REMOTE/

