#!/bin/bash
############################################################
# $Id: pkg 569 2013-04-19 06:16:16Z netkiller $
# $Author: netkiller $
# Homepage: http://netkiller.github.com/
############################################################
name="netkiller"
version="1.0.1"
release="1"
arch="all"

PKGNAME="$name""_""$version-$release""_$arch"
PREFIX=/tmp/neo
TMPDIR="$PREFIX/opt/neo/$name-$version"
PUBLIC_HTML=~/workspace/public_html
PACKAGE=/tmp

function mkrpm(){
	topdir=~/rpmbuild
	#rm -rf $topdir
	mkdir -p $topdir/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

	#echo "%_topdir ~/rpmbuild" > ~/.rpmmacros
	#echo "%_tmppath /tmp" > ~/.rpmmacros
	#echo "%packager Neo Chen <netkiller@msn.com>" > ~/.rpmmacros
	#cat ~/.rpmmacros

	rsync -auzv --delete --exclude=.git --exclude=.svn --exclude=download --exclude=zh-tw /home/neo/workspace/public_html/ /tmp/netkiller-1.0.1
	cd /tmp
	tar -zcvf $topdir/SOURCES/netkiller-1.0.1.tar.gz netkiller-1.0.1
	cd -

	#cd ${PUBLIC_HTML}/ && tar -zcvf $topdir/SOURCES/netkiller-1.0.1.tar.gz centos --exclude .git --exclude .svn --exclude download && cd -

	#cp rpmbuild/SPECS/package-1.0.spec $topdir/rpmbuild/SPECS/
	cat > $topdir/SPECS/package.spec <<RPM
#%define name netkiller
#%define version 1.0.1
Summary: Netkiller's eBook
Name: netkiller
Version: 1.0.1
Release: 1
License: CC
# group you want your package in, mostly for GUI package browsers
# some example groups used by vendors:
# http://www.rpmfind.net/linux/RPM/Groups.html
Group: Books/Computer books
Packager: Neo Chen <netkiller@msn.com>
#Source: http://netkiller.github.com/package/%{name}-%{version}.tar.gz
Source: %{name}-%{version}.tar.gz
URL: http://netkiller.github.io
# list all your patches here:
#Patch:
# list all packages required to build this package
#BuildRequires:
#Provides:
# list all packages that conflict with this one:
#BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}

####
# full length description
%description

http://netkiller.github.io
http://netkiller.sourceforge.net

- Network: Firewall, Router, Switch, Cisco, H3C, Juniper,F5 Big-IP, Array
- Security: OpenVPN, L2TP, PPTP, IPSec IP Tunnel
- Cluster: SmartDNS, LVS, HAproxy, Keepalived, Heartbeat, MooseFS, GlusterFS
- Web: Apache, Lighttpd, Nginx, Tomcat, Resin
- Database: PostgreSQL, MySQL Cluster, MySQL Replication, Cassandra, MongoDB
- Cache: APC Cache, XCache, Memcached, Squid, Varnish
- Frameworks: PHP(CodeIgniter, Prado, Mach II, Qcodo, Smarty)
- Python(Django, Pylons) Perl(Catalyst)
- Search Engine: Solr, Sphinx, Crawler: Nutch
- DIV-CSS, JQuery, Prototype, Google Map API
- Virtualization: Xen, Kvm, OpenVZ

#####
# this prepares a fresh build directory in ~/build/BUILD, useful macros here
# are:
# %setup - cleans any previous builds and untargzips the source
# %patch - applies patches
# any other commands here are executed as standard sh commands
%prep
#mkdir -p %{name}-%{version}
#if [ ! -f %{_sourcedir}/%{name}-%{version}-%{release}.tar.gz ]; then
#rsync -auzv --exclude=.git --exclude=.svn --exclude=download /home/neo/workspace/public_html/* %{name}-%{version}-%{release}
#tar -zcvf %{_sourcedir}/%{name}-%{version}-%{release}.tar.gz /home/neo/workspace/public_html/centos/*
#cd ${PUBLIC_HTML} && tar -zcvf %{_sourcedir}/%{name}-%{version}-%{release}.tar.gz * --exclude .git --exclude .svn --exclude download && cd -
#fi

%setup

#%patch

#####
# this tells rpmbuild how to build your package, rpmbuild runs it as a sh
# script
%build

mkdir -p %{_buildrootdir}/%{name}-%{version}-%{release}.x86_64/usr/share/doc/netkiller

#####
# all the steps necessary to install your package into $RPM_BUILD_ROOT
# first step is to clear $RPM_BUILD_ROOT
%install

rsync -auzv %{_builddir}/%{name}-%{version}/* %{_buildrootdir}/%{name}-%{version}-%{release}.x86_64/usr/share/doc/netkiller

#rsync -auzv ${PUBLIC_HTML}/mail/* %{_buildrootdir}/%{name}-%{version}-%{release}.x86_64/usr/share/doc/


#####
# NOTE: this section is optional
# commands run just before the package is installed
%pre
#/usr/sbin/useradd -c "test user" -r -s /bin/false -u 666 -d / neo 2> /dev/null

#####
# NOTE: this section is optional
# commands run before uninstalling the software
%preun
#/sbin/service test stop > /dev/null 2>&1
#/sbin/chkconfig --del test

#####
# NOTE: this section is optional
# commands run after installing the package
%post
#/sbin/chkconfig -add test
#touch /var/log/test

#####
# NOTE: this section is optional
# commands run after unistalling the package
%postun
#/sbin/service test stop
#/usr/sbin/userdel test

#####
# list all the files that are part of the package. If a file is not in the
# list rpmbuild won't put it in the package
# see below on how to automate the process of creating this list.
# some useful macros here:
# %doc /path/to/filename - installs filename into /path/to/filename and marks
# it as being documentation
# %config /etc/config_file - similar for configuration files
# %attr(mode, user, group) file - lets you specify file attributes applied
# during installation, use - if you want to use defaults
%files
# this will package the dir and all directories inside it
#/example/of/a/dir
/usr/share/doc

# this will package only the 'dir' directory
#%dir /example/of/a/dir
#%dir /

#####
# document changes between package releases
%changelog
RPM

	rpmbuild -ba $topdir/SPECS/package.spec
	#rpmbuild -bb $topdir/SPECS/package.spec
	echo "==================="
	rpm -qpl  ~/rpmbuild/RPMS/x86_64/*
	rpm -qpi  ~/rpmbuild/RPMS/x86_64/*
	echo "==================="
	rpm -qpl ~/rpmbuild/SRPMS/netkiller-1.0.1-1.src.rpm

#rpm -qpl：列出RPM软件包内的文件信息
#rpm -qpi：列出RPM软件包的描述信息
#rpm -Vp： 验证RPM软件包的内容

}


function deb(){
##########################################
# sudo dpkg -i netkiller.*.deb
# sudo dpkg -L netkiller
# sudo dpkg -r netkiller
##########################################

	echo $PKGNAME
	mkdir -p $TMPDIR
	rsync -auzv $PUBLIC_HTML/* $TMPDIR/
	mkdir -p $PREFIX/DEBIAN
	cat > $PREFIX/DEBIAN/control <<EOF
Package: netkiller
Version: $version-$release
Architecture: $arch
Maintainer: Neo Chen <netkiller@msn.com>
Installed-Size: 200M
Depends:
Section: doc
Priority: optional
Homepage: http://netkiller.github.io
Description: Netkiller ebook
 .
 Main editor: Neo Chen
 .
 Homepage: http://netkiller.github.io
 .
EOF
	mkdir -p $PUBLIC_HTML/download
	dpkg -b $PREFIX $PACKAGE/$PKGNAME.deb
}

function build(){
	deb
	rpm
}

function upload(){
#涓婃捣@Eden
ftp://admin:admin@209.236.120.168/
}


case "$1" in
	deb)
		deb
		;;
	rpm)
		mkrpm
		;;
	all)
		deb
		mkrpm
		;;
	*)
                echo $"Usage: $0 {all | deb | rpm}"
        	RETVAL=1
esac

exit $RETVAL
